version: '3.8'

services:
  web:
    build: .
    container_name: choir_web_app
    ports:
      - "1000:1000"
    volumes:
      - choir_data:/app/instance
      - choir_uploads:/app/uploads
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0

volumes:
  choir_data:
  choir_uploads: